baseURL = "https://traveling-bubbles.com/"
defaultContentLanguage = "en"
title = "Traveling bubbles!"
theme = "hugo_robust"
copyright = "Copyright (c) 2017, Theodiablo. All rights reserved."
canonifyurls = true
paginate = 4


[author]
  name = "Theodiablo"
  email = "admin@traveling-bubbles.com"

[params]
  disqusShortname = "travel-bubbles" # optional
  googleAnalyticsUserID = "UA-100203771-1"
  dateFormat = "2 January 2006"
  keywords = ["travel", "sightseeing", "backpacker"]
  sidebarBehavior = 2
  thumbnailImage = true
  thumbnailImagePosition = "right"
  autoThumbnailImage = true
  coverImage = "Floating-Bubbles-small.jpg"
  favicon = "favicon.png"
  imageGallery = true
  hierarchicalCategories = true
#  background = "world-map-color-opacity-cropped.jpg"

[Languages]
[Languages.en]
weight = 1
[Languages.en.params]

[Languages.fr]
weight = 2
[Languages.fr.params]
linkedin = "lien-francais"
dateFormat = "2 January 2006"
[Languages.fr.navigation]
help  = "Aide"

[Languages.es]
weight = 2
[Languages.es.params]
dateFormat = "2 January 2006"
[Languages.es.navigation]
help  = "Aide"


[outputs]
page = [ "HTML", "AMP" ] # if you want AMP enable.