baseURL = "https://www.traveling-bubbles.com/"
languageCode = "en-us"
title = "Traveling bubbles!"
theme = "hugo_theme_robust"
author = "Theodiablo"
copyright = "Copyright (c) 2017, Theodiablo; all rights reserved."
canonifyurls = true
paginate = 3


[params]
  disqusShortname = "travel-bubbles" # optional
  googleAnalyticsUserID = "UA-100203771-1"