baseURL = "https://traveling-bubbles.com/"
defaultContentLanguage = "es"
title = "Traveling bubbles!"
theme = "hugo_robust"
copyright = "Copyright (c) 2017, Theodiablo. All rights reserved."
canonifyurls = true
paginate = 4
googleAnalytics = "UA-100203771-1"
disqusShortname = "travel-bubbles"
enableRobotsTXT = true


[author]
  name = "Theodiablo"
  email = "admin@traveling-bubbles.com"

[params]
  dateFormat = "2 January 2006"
  keywords = ["travel", "sightseeing", "backpacker"]
  coverImage = "Floating-Bubbles-small.jpg"
  favicon = "favicon.png"
  # Fonts settings.
  googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700|Pacifico|Gloria+Hallelujah" # Optional, Include google fonts.
  fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif" # Optional, Override body font family.
  logofontfamily = "'Pacifico', cursive" # Optional, Override logo font.

[Languages]
  [Languages.en]
    weight = 1
    languageCode = "en-us"
  [Languages.en.params]

  [Languages.fr]
    weight = 2
    languageCode = "fr-fr"
  [Languages.fr.params]
    linkedin = "lien-francais"
    dateFormat = "2 January 2006"
    keywords = ["voyage", "visiter", "sac a dos"]
  [Languages.fr.navigation]
    help  = "Aide"

  [Languages.es]
    weight = 2
    languageCode = "es-es"
  [Languages.es.params]
    dateFormat = "2 January 2006"
    keywords = ["viaje", "visitar", "mochilero"]
  [Languages.es.navigation]
    help  = "Aide"


[outputs]
page = [ "HTML", "AMP" ] # if you want AMP enable.
home = [ "RSS" ]